Oscar
ofelcan164/CS547-P4 pull request #3
Opened 2021-12-09 01:20 UTC by ofelcan164

2021-12-09 02:33 UTC, ofelcan164 commented
Test

2021-12-09 02:37 UTC, njhoersch commented on libmfs.c
> +struct message {
Can we define this in `mfs.h` so we can pull it into the server code and this lib without redefining it?

2021-12-09 02:38 UTC, ofelcan164 commented on libmfs.c
> +struct message {
Yes. I was just worried about the fact that we shouldn't be including mfs.h in server code? Because in practice that wouldn't be possible?? or wouldn't be done

2021-12-09 02:41 UTC, njhoersch commented on libmfs.c
> +struct message {
Yeah I agree it maybe isn't the best practice for real-world use. We could do something like a `types.h` for all of P4 where we just define all structures and then have access to them where we need them?

2021-12-09 02:42 UTC, njhoersch commented on libmfs.c
> +    UDP_Read(sd, &addrRcv, buf, sizeof(ret_msg)); // TODO receive message in this way?
We might need to do a while loop here and read until we get a response, unless we can guarantee a response is ready from the server by the time we call this?

2021-12-09 02:43 UTC, ofelcan164 commented on libmfs.c
> +struct message {
That’s probably a better approach

2021-12-09 02:44 UTC, ofelcan164 commented on libmfs.c
> +    UDP_Read(sd, &addrRcv, buf, sizeof(ret_msg)); // TODO receive message in this way?
Fairly confident read just waits for a message but not 100% sure

2021-12-09 02:48 UTC, ofelcan164 commented on libmfs.c
> +    UDP_Read(sd, &addrRcv, buf, sizeof(ret_msg)); // TODO receive message in this way?
Based on the usage of read in the example client server communications

2021-12-09 02:49 UTC, njhoersch commented on libmfs.c
> +    UDP_Read(sd, &addrRcv, buf, sizeof(ret_msg)); // TODO receive message in this way?
`UDP_Read()` does not wait, but `recvfrom()` might. Will have to check more.

2021-12-09 02:52 UTC, njhoersch commented on libmfs.c
> +struct message {
- [ ] Move all structs to `type.h` and then include `type.h` where needed. (I can do this too, just putting this here as a way to track the thought.)

2021-12-09 03:35 UTC, njhoersch commented on libmfs.c
> +    UDP_Write(sd, &addrSnd, buf, BUFFER_SIZE);
It may be worth doing a check on the result of our `UDP_Write()` and `UDP_Read()` calls so that we can print an error if the call fails for some reason.

2021-12-09 03:35 UTC, njhoersch commented on libmfs.c
> +    struct message ret_msg = {};
Why initialize `ret_msg` to `{}` here and not above on line 73?

2021-12-09 03:35 UTC, njhoersch commented on libmfs.c
> +    struct message ret_msg = {};
Same question for `CREAT` function.

2021-12-09 03:42 UTC, njhoersch requested changes

2021-12-09 03:42 UTC, njhoersch commented on libmfs.c
> +    memcpy((struct message*)buf, &msg, sizeof(msg));
`memcpy` will always overflow here. `sizeof(msg)` will be roughly 100ish bytes bigger than the size of `buf`.

2021-12-09 04:58 UTC, ofelcan164 commented on libmfs.c
> +    struct message ret_msg = {};
initializing to {} stops the compiler from complaining basically. Otherwise it thinks it was never initialized. Maybe there is a better work around though.

2021-12-09 04:58 UTC, ofelcan164 commented on libmfs.c
> +    memcpy((struct message*)buf, &msg, sizeof(msg));
Smart

2021-12-09 16:36 UTC, ofelcan164 commented on libmfs.c
> +    UDP_Write(sd, &addrSnd, buf, BUFFER_SIZE);
Yeah sounds good. Wasn't sure if they actual return anything since its a UDP connection (i.e. non-reliable and potentially lossy).

2021-12-09 16:37 UTC, ofelcan164 commented on libmfs.c
> +    struct message ret_msg = {};
Also potentially could have a different return message struct that includes less information with just kind of basic success/fail stuff.

2021-12-09 16:40 UTC, ofelcan164 commented on libmfs.c
> +    memcpy((struct message*)buf, &msg, sizeof(msg));
Clearly the buffer we are sending needs to be larger than the buffer available to the user for read/write, correct? Or why is it that our buffer size has to be 1000 potentially. Maybe something to poke around piazza for. And maybe I am a little confused about the write buffer and its relation to the 4K block that is being written to.

2021-12-09 23:13 UTC, njhoersch commented on types.h
> +enum msg_type {INIT, LOOKUP, STAT, WRITE, READ, CREAT, UNLINK, SHUTDOWN};
What do you think of renaming this to request type?

2021-12-10 01:15 UTC, ofelcan164 commented on types.h
> +enum msg_type {INIT, LOOKUP, STAT, WRITE, READ, CREAT, UNLINK, SHUTDOWN};
Oh yeah

2021-12-10 04:01 UTC, njhoersch commented on libmfs.c
> +    int rc = UDP_Write(sd, &addrSnd, req_content, REQ_SIZE);
Like the name of req_content

2021-12-11 19:44 UTC, merged